rank1: "&l&bRank1"
ranks1Cost: 100
rank2: "&l&bRank2"
ranks2Cost: 80
rank3: "&l&bRank3"
ranks3Cost: 60
rank4: "&l&bRank4"
ranks4Cost: 40
rank5: "&l&bRank5"
ranks5Cost: 20
rank6: "&l&bRank6"
ranks6Cost: 10